# Generated by Django 2.1.7 on 2019-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20190518_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketslot',
            name='is_hot',
        ),
    ]
